spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 998b6dd7521a4a28d1670396ce95a479
            client-secret: TwC0gPzZWUGrwt5qOEye1OWGvRoXpAPq
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: oauth2
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id